In [ ]:
!pip3 install numpy

In [1]:
import numpy

a=numpy.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [2]:
import numpy as np

a=np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [5]:
import numpy as np

a=np.array(92)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
print(a)

print("Dimension =",a.ndim)

92
Dimension = 0


In [10]:
print(b)

print("Dimension =",b.ndim)

[1 2 3 4 5]
Dimension = 1


In [11]:
print(c)

print("Dimension =",c.ndim)

[[1 2 3]
 [4 5 6]]
Dimension = 2


In [12]:
print(x)

print("Dimension =",x.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension = 2


dtype parameter

In [13]:
import numpy as np

a= np.array([1,2,3],dtype=float) #float,str

print(a)

[1. 2. 3.]


how to access it

index array

In [14]:
import numpy as np

x=np.array([11,12,13,14,15,60,70,80,90,100])
print(x)

[ 11  12  13  14  15  60  70  80  90 100]


In [15]:
z=x[np.array([3,3,1,8])] #location values
print(z)

[14 14 12 90]


In [17]:
d=[1,2,3,4,5]
e=[5,6,7,8,9]
f=[2,45,32,78,65]
g=[3,6,8,9,2]
h=[66,99,88,33,22]

my_matrice=np.matrix([d,e,f,g,h])
my_matrice

matrix([[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  9],
        [ 2, 45, 32, 78, 65],
        [ 3,  6,  8,  9,  2],
        [66, 99, 88, 33, 22]])

In [18]:
my_matrice[1:4,2:5]

matrix([[ 7,  8,  9],
        [32, 78, 65],
        [ 8,  9,  2]])

In [19]:
li = [[1,2,3],[4,5,6],[7,8,9]] #list
ar=np.array(li) #numpy

print("list =",li)

print("numpy_array ="+"\n",ar)

list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_array =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
type(li)

list

In [21]:
type(ar)

numpy.ndarray

In [22]:
li+li

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [23]:
ar+ar

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [24]:
import numpy as np

k=np.array([3,4,5,6,8])
print(k)

[3 4 5 6 8]


In [26]:
copy1_=k.copy() #Making copy of original array

view1_=k.view() #Making view of original array

k[2]=90 #updating the original array

print("modified array =",view1_)

modified array = [ 3  4 90  6  8]


In [27]:
print("copied array =",copy1_)

print("viewes array =",view1_)

copied array = [3 4 5 6 8]
viewes array = [ 3  4 90  6  8]


In [28]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [29]:
print(arr.shape)

(12,)


In [31]:
newarr = arr.reshape(3,4)
print(newarr)
print(newarr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [33]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [35]:
np.arange(5,10)
print(a)

[1. 2. 3.]


In [36]:
np.arange(5,10,2)

array([5, 7, 9])

In [37]:
np.arange(10,30,2,float)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.])

In [38]:
#Reshaping the created array


In [39]:
x = np.linspace(0,5,3)
print(x)

[0.  2.5 5. ]


In [41]:
y = np.linspace(0,16,5)
print(y)

[ 0.  4.  8. 12. 16.]


max\min

In [1]:
a= np.array([(1,2,3),(3,4,5)])
#not complete

NameError: name 'np' is not defined

row of column,sum and mean

In [3]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x.sum()

45

In [5]:
x.sum(axis=0) #column sum

array([12, 15, 18])

In [6]:
x.sum(axis=1) #row sum

array([ 6, 15, 24])

In [7]:
x.mean(axis=0) #column mean

array([4., 5., 6.])

zeroes, ones and empty

In [9]:
a = np.zeros((3,5),dtype=float)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
x=np.empty([3,2],dtype=int)
print(x) #the elements is in an array shows random values...

[[         0 1074790400]
 [         0 1075052544]
 [         0 1075314688]]


numpy.asarray

list to numpy

In [15]:
import numpy as np

x= [1,2,3] #list

print(x,type(x))

[1, 2, 3] <class 'list'>


In [13]:
a= np.asarray(x) #int
print(a,type(a))

[1 2 3] <class 'numpy.ndarray'>


In [14]:
a=np.asarray(x,dtype=float)
print(a,type(a))

[1. 2. 3.] <class 'numpy.ndarray'>


how can we join two arrays?

In [17]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


hstack vs vstack

In [22]:
a=np.array([21,32,45])
b=np.array([98,23,34])

In [23]:
s=np.hstack((a,b))

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==5)
print(x)

(array([4], dtype=int64),)


In [26]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
np.where(a<5,a,10*a) #values of a < 5 will be printed

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [29]:
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [30]:
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


Function for integers

In [33]:
from numpy import random
x=random.randint(10) #random number
print(x)

4


In [34]:
y= random.randint(5,10)
print(y)

9


In [35]:
from numpy import random

x=random.randint(1000,size=(6)) # generate a 1-D array containing 5 random integers
print(x)

[777 925  95 935 549 209]


In [37]:
x= random.randint(100,size=(3,5)) # genertae a 2-D array with 3 rows...
print(x)

[[40  0 62 26 72]
 [86 82  1  3  8]
 [29 56 99 44 80]]


real-valued distribution

In [38]:
from numpy import random
x=random.rand() #random float 0.0 <= x< 1.0
print(x)

0.8188523329781506


Function for sequences

In [39]:
from numpy import random
x=random.choice([3,5,7,9])
print(x)

7


In [41]:
from numpy import random
x=random.choice([3,5,7,9],size=(3,)) 
print(x)

[9 3 9]


Broadcasting

In [42]:
import numpy as np
my_array=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [43]:
my_array[0:5]=22

In [44]:
my_array

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])