Practice Questions
1. Create a numpy array filled with all ones by defining its shape.
2. How do you remove rows from a Numpy array that contains non-numeric values?
3. Remove single-dimensional entries from the shape of an array
4. How do you check whether specified values are present in the NumPy array?
5. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis, and
flattened array.
6. Write a NumPy program to create a structured array from a given student name, height,
class, and data type. Now sort by class, then height if the classes are equal.
7. Write a NumPy program to sort a given complex array using the real part first, then the
imaginary part.
8. Write a NumPy program to sort a given array by the nth column.
9. Calculate the sum of the diagonal elements of a NumPy array
10. Write a program for Matrix Multiplication in NumPy
11. Multiply matrices of complex numbers using NumPy in Python
12. Compute the covariance matrix of two given NumPy arrays.
13. Convert covariance matrix to correlation matrix using Python
14. Write a NumPy program to compute the histogram of nums against the bins.
15. Write a NumPy program to compute the cross-correlation of two given arrays
16. Write a NumPy program to compute the mean, standard deviation, and variance of a
given array along the second axis.

In [1]:
#1
import numpy as np

arr = np.ones((3, 4))  # 3x4 array filled with ones
print(arr)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#2
arr = np.array([["1", "2"], ["3", "x"], ["4", "5"]])

mask = np.array([np.char.isnumeric(row).all() for row in arr])
cleaned = arr[mask]
print(cleaned.astype(int))

[[1 2]
 [4 5]]


In [4]:
#3
arr = np.array([[[1], [2], [3]]])
print("Original shape:", arr.shape)
squeezed = np.squeeze(arr)
print("After squeeze:", squeezed.shape)


Original shape: (1, 3, 1)
After squeeze: (3,)


In [5]:
#4
arr = np.array([1, 2, 3, 4, 5])
print(3 in arr)       # True
print(np.isin([2, 6], arr))  # [True, False]

True
[ True False]


In [6]:
#5
arr = np.array([[3, 1, 2], [6, 4, 5]])

print("Sort along first axis:\n", np.sort(arr, axis=0))
print("Sort along last axis:\n", np.sort(arr, axis=-1))
print("Flattened sort:\n", np.sort(arr, axis=None))

Sort along first axis:
 [[3 1 2]
 [6 4 5]]
Sort along last axis:
 [[1 2 3]
 [4 5 6]]
Flattened sort:
 [1 2 3 4 5 6]


In [7]:
#6
data = np.array([("Alice", 5.5, 10), 
                 ("Bob", 5.8, 9), 
                 ("Charlie", 5.7, 10)],
                 dtype=[("name", "U10"), ("height", "f4"), ("class", "i4")])

sorted_data = np.sort(data, order=["class", "height"])
print(sorted_data)

[('Bob', 5.8,  9) ('Alice', 5.5, 10) ('Charlie', 5.7, 10)]


In [8]:
#7
arr = np.array([2+3j, 1+2j, 2+1j, 1+4j])
sorted_arr = np.sort_complex(arr)
print(sorted_arr)

[1.+2.j 1.+4.j 2.+1.j 2.+3.j]


In [9]:
#8
arr = np.array([[3, 7, 1], [2, 6, 5], [9, 4, 8]])
n = 1  # sort by 2nd column
sorted_arr = arr[arr[:, n].argsort()]
print(sorted_arr)

[[9 4 8]
 [2 6 5]
 [3 7 1]]


In [10]:
#9
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(np.trace(arr))  # 1+5+9 = 15

15


In [11]:
#10
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [12]:
#11
A = np.array([[1+2j, 2+3j], [3+4j, 4+5j]])
B = np.array([[5+6j, 6+7j], [7+8j, 8+9j]])

C = np.matmul(A, B)
print(C)

[[-17. +53.j -19. +61.j]
 [-21.+105.j -23.+121.j]]


In [13]:
#12
x = np.array([2, 4, 6, 8])
y = np.array([1, 3, 5, 7])

cov_matrix = np.cov(x, y)
print(cov_matrix)

[[6.66666667 6.66666667]
 [6.66666667 6.66666667]]


In [14]:
#13
cov = np.cov(x, y)
stddev = np.sqrt(np.diag(cov))
corr = cov / np.outer(stddev, stddev)
print(corr)

[[1. 1.]
 [1. 1.]]


In [15]:
#14
nums = np.array([1, 2, 1, 3, 2, 4, 3, 3, 2, 1])
hist, bins = np.histogram(nums, bins=[0,1,2,3,4,5])
print("Histogram:", hist)
print("Bins:", bins)

Histogram: [0 3 3 3 1]
Bins: [0 1 2 3 4 5]


In [16]:
#15
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])

cross_corr = np.correlate(a, b, mode="full")
print(cross_corr)

[0.5 2.  3.5 3.  0. ]


In [17]:
#16
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print("Mean:", np.mean(arr, axis=1))
print("Std:", np.std(arr, axis=1))
print("Var:", np.var(arr, axis=1))

Mean: [2. 5. 8.]
Std: [0.81649658 0.81649658 0.81649658]
Var: [0.66666667 0.66666667 0.66666667]
